App: # Application config
    Name: igeSample # App Name: must not contains space
    Label: Sample # App Label: Icon label, can contains space
    VersionName: '0.0.1' # (major.minor.build)
    VersionCode: 1 # MUST BE INTEGER (without leading '0' character)
    BundleId: net.indigames.igesample # BundleID (iOS/MacOS), Package Name (Android)

Platforms: # Platforms config
    android:
        RomDir: rom/mobile
        ConfigDir: config/android # Android 'res' folder
        arm64-v8a: true
        x86_64: false
        MinSdkVersion: 21
        TargetSdkVersion: 31
        ScreenOrientation: portrait
        Permissions:
            - android.permission.INTERNET  # Access internet
            - android.permission.ACCESS_NETWORK_STATE # Access network state
            - android.permission.ACCESS_WIFI_STATE # Access WIFI state
            - android.permission.WRITE_EXTERNAL_STORAGE # R/W access to external storage
            - android.permission.VIBRATE # Vibration permission
            # - android.permission.CAMERA # Camera permission
            # - android.permission.BLUETOOTH # Bluetooth permission
            # - add more here
        Features:
            android.hardware.touchscreen: true # Use touch screen, required
            # android.hardware.camera: true # Use camera, required
            # android.hardware.camera.autofocus: false # Use camera auto focus, not required
            # - add more here
    windows:
        RomDir: rom/pc
        ConfigDir: ''
        x64: true
    ios:
        RomDir: rom/mobile
        ConfigDir: config/ios # iOS's 'Assets' folder
        arm64: true
        DeploymentTarget: '11.0'
        DeviveFamily: 1,2
        DevelopmentTeamID: R2TWY42MN5
        CodeSignIdentity: iPhone Development # use 'iPhone Development' for debug, 'iPhone Distribution' for release
        ProvisioningProfile: Automatic # use 'Automatic' for debug, 'igeSample-Adhoc-IOS' for release
    macos:
        RomDir: rom/pc
        ConfigDir: ''
        x64: true

Requires: # Modules config
    - igePAL/[>=0.0.6]@ige/test
    - igeBullet/[>=0.4.61]@ige/test 
    - igeEffekseer/[>=0.1.6]@ige/test
    - igeNavigation/[>=0.0.2]@ige/test
    - igeScene/[>=0.0.6]@ige/test
    - igeSound/[>=0.1.0]@ige/test
    - igeSdk/[>=0.0.1]@ige/test
    - igeGamesServices/[>=0.0.1]@ige/test
    - igeSocial/[>=0.0.5]@ige/test
    - igeWebview/[>=0.0.3]@ige/test
    - igeFirebase/[>=0.0.33]@ige/test
    - igeNotify/[>=0.0.1]@ige/test
    - pyimgui/[>=1.2.0]@ige/test
    - dlib/[>=19.19.99]@ige/test
    - opencv/[>=4.1.2]@ige/test
    - pybox2d/[>=2.3.8]@ige/test
    - pillow/[>=8.2.0]@ige/test
    - tensorflow/[>=2.5.0]@ige/test

