App: # Application config
    Name: igeSample # App Name: must not contains space
    Label: Sample # App Label: Icon label, can contains space
    VersionName: '0.0.1' # Version Name (major.minor.build + a-z)
    VersionCode: 100 # Version Code ([1][0][0][00] <=> [Major][Minor][Build][0 - 24])
    BundleId: net.indigames.igesample # BundleID (iOS/MacOS), Package Name (Android)

Platforms: # Platforms config
    android:
        RomDir: rom/mobile
        ConfigDir: config/android # Android 'res' folder
        arm64-v8a: true
        x86_64: false
        MinSdkVersion: 21
        TargetSdkVersion: 30
        ScreenOrientation: portrait
        Permissions:
            - android.permission.INTERNET  # Access internet
            - android.permission.ACCESS_NETWORK_STATE # Access network state
            - android.permission.ACCESS_WIFI_STATE # Access WIFI state
            - android.permission.WRITE_EXTERNAL_STORAGE # R/W access to external storage
            # - android.permission.CAMERA # Camera permission
            - android.permission.VIBRATE # Vibration permission
            # - android.permission.BLUETOOTH # Bluetooth permission
            # - add more here
        Features:
            android.hardware.touchscreen: true # Use touch screen, required
            # android.hardware.camera: true # Use camera, required
            # android.hardware.camera.autofocus: false # Use camera auto focus, not required
            # - add more here
    windows:
        RomDir: rom/pc
        ConfigDir: ''
        x64: true
    ios:
        RomDir: rom/mobile
        ConfigDir: config/ios # iOS's 'Assets' folder
        arm64: true
        DeploymentTarget: '11.0'
        DeviveFamily: 1,2
        DevelopmentTeamID: R2TWY42MN5
        CodeSignIdentity: iPhone Development
        ProvisioningProfile: Automatic # use 'Automatic' for development
    macos:
        RomDir: rom/pc
        ConfigDir: ''
        x64: true

Requires: # Modules config
    - igeCore/[>=0.5.68]@ige/test
    - pyxCore/[>=0.5.68]@ige/test
    - SDL/[>=2.0.11]@ige/test
    - stb/[>=1.0.0]@ige/test
    - openssl/[>=1.1.1c]@ige/test
    - taskflow/[>=3.1.0]@ige/test
    - tracy/[>=0.6.6]@ige/test
    - Python/[>=3.9.1]@ige/test
    - numpy/[>=1.19.5]@ige/test
    - igePAL/[>=0.0.6]@ige/test
    - bullet/[>=3.0.8]@ige/test
    - igeBullet/[>=0.4.61]@ige/test 
    - igeEffekseer/[>=0.1.6]@ige/test
    - igeNavigation/[>=0.0.2]@ige/test
    - igeScene/[>=0.0.6]@ige/test
    - igeSound/[>=0.1.0]@ige/test
    - igeGameAnalytics/[>=0.0.3]@ige/test
    # - pyimgui/[>=1.2.0]@ige/test
    # - dlib/[>=19.19.99]@ige/test
    # - igeDlibExt/[>=0.0.1]@ige/test
    # - opencv/[>=4.1.2]@ige/test
    # - pybox2d/[>=2.3.8]@ige/test
    # - pillow/[>=8.2.0]@ige/test
    # - tensorflow/[>=2.5.0]@ige/test
    # - igeAdjust/[>=0.0.5]@ige/test
    # - igeAds/[>=0.0.3]@ige/test
    # - igeAppsFlyer/[>=0.0.2]@ige/test
    # - igeAutoTest/[>=0.0.4]@ige/test
    # - igeCamera/[>=0.0.1]@ige/test
    # - igeFirebase/[>=0.0.33]@ige/test
    # - igeGamesServices/[>=0.0.1]@ige/test
    # - igeInAppPurchase/[>=0.0.2]@ige/test
    # - igeNanoGUI/[>=0.0.1]@ige/test
    # - igeNotify/[>=0.0.1]@ige/test
    # - igeSocial/[>=0.0.5]@ige/test
    # - igeWebview/[>=0.0.3]@ige/test

