App: # Application config
    Name: igeSample # App Name: must not contains space
    Label: Sample # App Label: Icon label, can contains space
    VersionName: '0.0.1' # (major.minor.build)
    VersionCode: 1 # MUST BE INTEGER (without leading '0' character)
    BundleId: net.indigames.igesample # BundleID (iOS/MacOS), Package Name (Android)
    Orientation: 'portrait' # 'landscape' or 'portrait'

Platforms: # Platforms config
    android:
        RomDir: 'mobile'
        ConfigDir: 'config/android' # Android 'res' folder
        arm64-v8a: true
        armeabi-v7a: true
        MinSdkVersion: 21
        TargetSdkVersion: 31
        ScreenOrientation: portrait
        Permissions:
            - android.permission.INTERNET  # Access internet
            - android.permission.ACCESS_NETWORK_STATE # Access network state
            - android.permission.ACCESS_WIFI_STATE # Access WIFI state
            - android.permission.WRITE_EXTERNAL_STORAGE # R/W access to external storage
            - android.permission.VIBRATE # Vibration permission
            # - android.permission.CAMERA # Camera permission
            # - android.permission.BLUETOOTH # Bluetooth permission
            # - add more here
        Features:
            android.hardware.touchscreen: true # Use touch screen, required
            # android.hardware.camera: true # Use camera, required
            # android.hardware.camera.autofocus: false # Use camera auto focus, not required
            # - add more here
    windows:
        RomDir: 'pc'
        ConfigDir: 'config/windows'
        x64: true
    ios:
        RomDir: 'mobile'
        ConfigDir: 'config/ios' # iOS's 'Assets' folder
        arm64: true
        DeploymentTarget: '11.0'
        DeviveFamily: 1,2
        DevelopmentTeamID: R2TWY42MN5
        CodeSignIdentity: iPhone Development # use 'iPhone Development' for debug, 'iPhone Distribution' for release
        ProvisioningProfile: Automatic # use 'Automatic' for debug, 'igeSample-Adhoc-IOS' for release
    macos:
        RomDir: 'pc'
        ConfigDir: 'config/macos'
        x64: true
    emscripten:
        RomDir: 'mobile'
        ConfigDir: 'config/emscripten'

Requires: # Modules config
    - igePAL
    - igeBullet
    - igeEffekseer
    - igeNavigation
    - igeScene
    - igeSound
    - igeSdk
    # - igeGamesServices
    # - igeSocial
    # - igeWebview
    # - igeFirebase
    # - igeNotify
    # - pyimgui
    # - dlib
    # - opencv
    # - pybox2d
    # - pillow
    # - tensorflow

