# igeSdk_FOUND
# igeSdk_LIBRARIES
# igeSdk_INCLUDE_DIRS

set(igeSdk_FOUND 1)
set(igeSdk_COMPILE_DEFINITIONS "-DUSE_IGESDK")
set(igeSdk_BASE_DIR "${CMAKE_CURRENT_LIST_DIR}/../libs/igeSdk")

if(USE_PREBUILT_LIBS)
    set(PLATFORM "windows")
    set(ARCH "x86_64")
    if(DEFINED ANDROID_PLATFORM)
        set(PLATFORM "android")
        if(ANDROID_ABI STREQUAL "armeabi-v7a")
            set(ARCH "armv7")
        elseif(ANDROID_ABI STREQUAL "x86")
            set(ARCH "x86")
        elseif(ANDROID_ABI STREQUAL "arm64-v8a")
            set(ARCH "armv8")
        elseif(ANDROID_ABI STREQUAL "x86_64")
            set(ARCH "x86_64")
        endif()
    elseif(MSVC)
        set(PLATFORM "windows")
        if( CMAKE_SIZEOF_VOID_P EQUAL 8 )
            set(ARCH "x86_64")
        else()
            set(ARCH "x86")
        endif()
    elseif(EMSCRIPTEN)
        set(PLATFORM "emscripten")
        set(ARCH "wasm")
    elseif(APPLE)
        if(IOS)
            set(PLATFORM "ios")
            set(ARCH "arm8")
        else()
            set(PLATFORM "macos")
            set(ARCH "x86_64")
        endif()
    endif()    
    set(CMAKE_MODULE_PATH "${igeSdk_BASE_DIR}/cmake" "${CMAKE_MODULE_PATH}")
    include(FindPython)
    include(Findjson)
    set(igeSdk_INCLUDE_DIRS "${igeSdk_BASE_DIR}/prebuilt/${PLATFORM}/${ARCH}/include" ${json_INCLUDE_DIRS})
    set(igeSdk_LIB_DIRS "${igeSdk_BASE_DIR}/prebuilt/${PLATFORM}/${ARCH}/lib" ${Python_LIB_DIRS})
    set(igeSdk_LIBRARIES "igeSdk-static" ${Python_LIBRARIES})
else()
    if(NOT TARGET igeSdk-static)
        add_subdirectory("${igeSdk_BASE_DIR}" "${CMAKE_BINARY_DIR}/igeSdk" EXCLUDE_FROM_ALL)
    endif()
    set(igeSdk_INCLUDE_DIRS "${igeSdk_BASE_DIR}")
    set(igeSdk_LIBRARIES "igeSdk-static")
endif()
